"""
Django settings for youtube_api project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l-un4c2#5g1lrj+4^qtfhsmm1b%bug*q_%rk!sepvol2b4_-73'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

CORS_ORIGIN_ALLOW_ALL=True

CORS_ALLOWED_ORIGINS = [

    "http://localhost:8080",
    "http://127.0.0.1:9000",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
]

CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'Authorization',
    'content-type',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    # 'Token', # Add any custom headers here
]



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'search',
    'rest_framework',
    'django_filters',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

# settings.py
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'

from datetime import timedelta
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'youtube-api-request-every-30-seconds': {
        'task': 'search.tasks.youtube_api_request',
        'schedule': timedelta(seconds=30),
    },
}


ROOT_URLCONF = 'youtube_api.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'youtube_api.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

YOUTUBE_DATA_API_KEYS = ['AIzaSyBzW714KfsqGTEVMfDB0Yhsqq4x7qN255M', 'AIzaSyBND1As-Rly8Cxe1hjl-djP1MJwKcsupbw', 'AIzaSyBOs6pe1H_xAPYpRSbaLwNOxqC6Hvruh7E', 'AIzaSyAk9Tk-m6GZ6OCSMlOOwyhz5ui-9VL_7so','AIzaSyBImoTepAKTtkKuCNWgcXyAjCBByn806Lc','AIzaSyCEKD42ehcTXIGBkCn8kCnYr9yrjt2j9_I','AIzaSyDn0wbm40ds5INTZA7nTh2ym-7isjwZFj0','AIzaSyCNsiTh75CUB2wK0RK9HDnbHvVYvly_ga4','AIzaSyDD4vhpo1kTzSZioUl2WsK3Jua3Mt99q6U','AIzaSyCp1JoAL1b5_qo8zwaczR3eB3B-tYtKoaU','AIzaSyBh62TZvxSp9YjgtaCF1BCSrVC36qKPk5Y','AIzaSyAift4ERkPf9CPub804rVXGOQZaSmzF5R0','AIzaSyBRrMJNPejcShw5k0FAhFDxAwRM2NVopwI','AIzaSyD6lrBYGy0CtpWsjMqOkI7AfCCfMSouCPw','AIzaSyBkBC8jyw-fDVnRWBH-umYrUpix8fWg0nk', 'AIzaSyAzfCEA_ABbUFPXTH1R-y4vi7njVmfV0oM', 'AIzaSyCS_SDIv2O-cUAPfG0FrWKLNcP0ChuX8_o','AIzaSyCPYzChNw5UdG88GZunZgVPFReruXQGRz8','AIzaSyAj-40I594ELwrL-K3GTCC4pmMB4nHJdjU','AIzaSyDtMNw10OFBaLbxKi-2j07jJP-zjxWS4eQ','AIzaSyCzdqlqqlO5gFP95cu6CG_hRewAFvVWLLw','AIzaSyBhZYgJsCaDoUwg6CrupmkwFWUgd3XRNbI', 'AIzaSyA998H2Niqpu_WuDioawNuc7X6at5NqsrI','AIzaSyBljwXmwqfX9e5d0SxdYKB_TcyL33TmCns','AIzaSyAdnLF-w8EUQ3aoEqR7aNjAnWIP242P3mo','AIzaSyAKnIjyMe-MpjIBTtZShB4_tCfI5Q2Ggo8','AIzaSyC_FX1Eydz9_E1x5_e9pnVBXqU3bfV3xak','AIzaSyC_CD6pjKUPIdp3oy_cFaVKbqeUl_rouEo','AIzaSyCUtpi-5o1YjqBHyKkjAoN_IomIBbAayPI','AIzaSyAWYqmc9iUnB4UKuFynMZ7UAcmEjJtlbe8','AIzaSyCxRANWH8JNyPqGM23f3RLqbNjQUNJ1F2k','AIzaSyBmaZytvm2toB9ysCoMPUKdupPcXVPu1B0','AIzaSyA2BGRBoq725VHEmPQVAbX9L21NJjTdFfg','AIzaSyB44sMrb5Iwslruyh6-gLiKezFtiBD2CUw','AIzaSyDp-yqbssExdyJ5gF_4T9qPOHIGhpg35hc','AIzaSyDGlYG0rOlkzKJ7lzvION9WwkE_bRzU0-I','AIzaSyBZ2Cn_yv_Cbbqh2aqtMEV-YdNrL7Jn2dA','AIzaSyCt4N8FKyw1c1MHAjir5wetpqKh5rIn0Ls','AIzaSyDxgMq387s4-GADqFlH33xJpaPpEX8qVfA','AIzaSyD1uL_pWCzumoSNqT4V6O4JvAX0p42onX4','AIzaSyCPTjLfaJaVKzPDAEx0KijeWE6a7JAxYLM','AIzaSyAiI952UN2EN4AQcfyLlQykMmk3WSZAOgM']
